declare module 'editorjs-alert';
declare module '@editorjs/underline';
declare module 'editorjs-change-case';
declare module '@sotaproject/strikethrough';
declare module '@editorjs/checklist';
declare module '@editorjs/simple-image';
declare module '@editorjs/embed';
declare module '@editorjs/marker';
declare module '@editorjs/inline-code';
declare module '@editorjs/list';
declare module '@editorjs/header';
declare module '@editorjs/paragraph';
declare module 'editorjs-text-color-plugin';
declare module 'editorjs-text-alignment-blocktune'